### ISSUE TITLE
reason?

### ISSUE THREAD

**Issue by NickKruto** [Meowhal/osu-ahr#152]
[00:26:35.134][ERROR] discord_bot - @DiscordBot#make
Invalid Webhook Token
DiscordAPIError: Invalid Webhook Token
    at RequestHandler.execute (C:\osu-ahr-dev\node_modules\discord.js\src\rest\RequestHandler.js:350:13)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async RequestHandler.push (C:\osu-ahr-dev\node_modules\discord.js\src\rest\RequestHandler.js:51:14)
    at async InteractionWebhook.editMessage (C:\osu-ahr-dev\node_modules\discord.js\src\structures\Webhook.js:325:15)
    at async CommandInteraction.editReply (C:\osu-ahr-dev\node_modules\discord.js\src\structures\interfaces\InteractionResponses.js:139:21)
    at async DiscordBot.make (C:\osu-ahr-dev\dist\discord\DiscordBot.js:143:13)
    at async DiscordBot.handleCommandInteraction (C:\osu-ahr-dev\dist\discord\DiscordBot.js:99:17)
    at async Client.<anonymous> (C:\osu-ahr-dev\dist\discord\DiscordBot.js:53:17)
C:\osu-ahr-dev\node_modules\discord.js\src\rest\RequestHandler.js:350
      throw new DiscordAPIError(data, res.status, request);
            ^

DiscordAPIError: Invalid Webhook Token
    at RequestHandler.execute (C:\osu-ahr-dev\node_modules\discord.js\src\rest\RequestHandler.js:350:13)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async RequestHandler.push (C:\osu-ahr-dev\node_modules\discord.js\src\rest\RequestHandler.js:51:14)
    at async InteractionWebhook.editMessage (C:\osu-ahr-dev\node_modules\discord.js\src\structures\Webhook.js:325:15)
    at async CommandInteraction.editReply (C:\osu-ahr-dev\node_modules\discord.js\src\structures\interfaces\InteractionResponses.js:139:21)
    at async DiscordBot.make (C:\osu-ahr-dev\dist\discord\DiscordBot.js:147:13)
    at async DiscordBot.handleCommandInteraction (C:\osu-ahr-dev\dist\discord\DiscordBot.js:99:17)
    at async Client.<anonymous> (C:\osu-ahr-dev\dist\discord\DiscordBot.js:53:17) {
  method: 'patch',
  path: '/webhooks/1036633040090312714/aW50ZXJhY3Rpb246MTAzNjcxODI5MTAxMzYxMTU3MTpxOG9UbVk5czlMOThWR0lIcVRXRlEySXloOHpVUDNOeXhveDRjYjVhR1RURTY5QXZyb3pqWmJxb1lZT2VtRlJndDFCZ1gxUDRXSXZDTUJaRHdvR0NkcDI1YWQ3aHdwM3p2a3pKQXRrVkhJMjkxeHJhUjZWdVhXb0hoU0NDUXF1dw/messages/@original',
  code: 50027,
  httpStatus: 401,
  requestData: {
    json: {
      content: 'There was an error while making a discord channel. Invalid Webhook Token',
      tts: false,
      nonce: undefined,
      embeds: undefined,
      components: undefined,
      username: undefined,
      avatar_url: undefined,
      allowed_mentions: undefined,
      flags: undefined,
      message_reference: undefined,
      attachments: undefined,
      sticker_ids: undefined
    },
    files: []
  }
}

**Comment by xayanide** [comment]
An error has occured during creation of a lobby, it wasn't able to edit the reply to inform that the lobby is created, the try catch does its job, the catch clause also has an `editReply()` method but for the second time the discord bot tried to edit a reply that wasn't sent. I have no idea as to why the reply wasn't sent, care to elaborate more?

Don't worry, that doesn't crash the bot because something like that is expected to happen, you should just ignore the error.

If an error in particular crashes the bot, that's when you should make an issue about it.

**Comment by NickKruto** [comment]
The error causes disconnection from irc and discord. And I also noticed, at least through discord, that the lobby can only be created using English letters, otherwise the lobby will be created without a name, which will lead to another error.
