### ISSUE TITLE
Can't start the bot

### ISSUE THREAD

**Issue by flapczek** [Meowhal/osu-ahr#161]
When im starting the bot im getting this:

Loading log4js configuration from ./config/log_cli.json
D:\Kamil\osu-ahr-master\osu-ahr-master\node_modules\config\lib\config.js:844
    throw new Error("Cannot parse config file: '" + fullFilename + "': " + e3);
    ^

Error: Cannot parse config file: 'D:\Kamil\osu-ahr-master\osu-ahr-master\config\local.json': SyntaxError: Unexpected number in JSON at position 1681
    at Config.util.parseFile (D:\Kamil\osu-ahr-master\osu-ahr-master\node_modules\config\lib\config.js:844:11)
    at D:\Kamil\osu-ahr-master\osu-ahr-master\node_modules\config\lib\config.js:644:26
    at Array.forEach (<anonymous>)
    at Config.util.loadFileConfigs (D:\Kamil\osu-ahr-master\osu-ahr-master\node_modules\config\lib\config.js:643:16)
    at new Config (D:\Kamil\osu-ahr-master\osu-ahr-master\node_modules\config\lib\config.js:116:27)
    at Object.<anonymous> (D:\Kamil\osu-ahr-master\osu-ahr-master\node_modules\config\lib\config.js:1492:31)
    at Module._compile (node:internal/modules/cjs/loader:1126:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1180:10)
    at Module.load (node:internal/modules/cjs/loader:1004:32)
    at Function.Module._load (node:internal/modules/cjs/loader:839:12)

**Comment by Bibou1494** [comment]
Hello. Do you have do ```npm install``` with a terminal first ?
