### ISSUE TITLE
 Cannot parse config file: 'C:\Users\jaide\osu-ahr\config\local.json': SyntaxError: Unexpected token k in JSON at position 173

### ISSUE THREAD

**Issue by kzwa01** [Meowhal/osu-ahr#167]
i get this everytime i try running osu-ahr

```
C:\Users\jaide\osu-ahr>npm start

> osu-ahr@1.6.1 start
> node dist/cli/index.js

Loading log4js configuration from ./config/log_cli.json
C:\Users\jaide\osu-ahr\node_modules\config\lib\config.js:844
    throw new Error("Cannot parse config file: '" + fullFilename + "': " + e3);
    ^

Error: Cannot parse config file: 'C:\Users\jaide\osu-ahr\config\local.json': SyntaxError: Unexpected token k in JSON at position 173
    at util.parseFile (C:\Users\jaide\osu-ahr\node_modules\config\lib\config.js:844:11)
    at C:\Users\jaide\osu-ahr\node_modules\config\lib\config.js:644:26
    at Array.forEach (<anonymous>)
    at util.loadFileConfigs (C:\Users\jaide\osu-ahr\node_modules\config\lib\config.js:643:16)
    at new Config (C:\Users\jaide\osu-ahr\node_modules\config\lib\config.js:116:27)
    at Object.<anonymous> (C:\Users\jaide\osu-ahr\node_modules\config\lib\config.js:1492:31)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)

Node.js v18.17.1
```

**Comment by xayanide** [comment]
hi there! It looks like there might be a problem with the local.json file based on the error log. It seems there could be mistakes or changes in the way it's written.

could you try creating a new `local.json` file by copying the content from `default.json`? After that, set only your credentials, give it another shot and see if it works.

if you can, please share the content of that `local.json` file here, but **please be sure to EXCLUDE any sensitive information like credentials**.

please provide more information on this as it is currently not enough for me to conclude what the problem actually is.
