### ISSUE TITLE
map checking error? the error 

### ISSUE THREAD

**Issue by Tali13** [Meowhal/osu-ahr#20]
[17:04:16.386][ERROR] his_repo - @updateToLatest : Request failed with status code 429

C:\Users\trand\Desktop\osu-ahr-dev\node_modules\axios\lib\core\createError.js:16
  var error = new Error(message);
              ^
Error: Request failed with status code 429
    at createError (C:\Users\trand\Desktop\osu-ahr-dev\node_modules\axios\lib\core\createError.js:16:15)
    at settle (C:\Users\trand\Desktop\osu-ahr-dev\node_modules\axios\lib\core\settle.js:17:12)
    at IncomingMessage.handleStreamEnd (C:\Users\trand\Desktop\osu-ahr-dev\node_modules\axios\lib\adapters\http.js:260:11)
    at IncomingMessage.emit (node:events:406:35)
    at IncomingMessage.emit (node:domain:470:12)
    at endReadableNT (node:internal/streams/readable:1331:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)

**Comment by Tali13** [comment]
can u help me fix it ?

**Comment by Tali13** [comment]
and ty for create this bot

**Comment by Meowhal** [comment]
thx for reporting.
i fixed the bug.
it should not hang again in version 1.4.6.
you can update your bot using the `git pull` command.

**Comment by Tali13** [comment]
ty
