### ISSUE TITLE
Discord integration not working

### ISSUE THREAD

**Issue by capthusky** [Meowhal/osu-ahr#30]
Tried to run start:discord but it's not working with Unhandled Promise Rejection Warning

(node:10948) UnhandledPromiseRejectionWarning: ReferenceError: AbortController is not defined
    at RequestHandler.execute (C:\Users\test\Desktop\osu-ahr-master\node_modules\discord.js\src\rest\RequestHandler.js:172:15)
    at RequestHandler.execute (C:\Users\test\Desktop\osu-ahr-master\node_modules\discord.js\src\rest\RequestHandler.js:176:19)
    at RequestHandler.push (C:\Users\test\Desktop\osu-ahr-master\node_modules\discord.js\src\rest\RequestHandler.js:50:25)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at WebSocketManager.connect (C:\Users\test\Desktop\osu-ahr-master\node_modules\discord.js\src\client\websocket\WebSocketManager.js:128:9)
    at Client.login (C:\Users\test\Desktop\osu-ahr-master\node_modules\discord.js\src\client\Client.js:245:7)
    at DiscordBot.start (C:\Users\test\Desktop\osu-ahr-master\src\discord\DiscordBot.ts:87:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:10948) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:10948) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

Any fixes?

**Comment by Meowhal** [comment]
Thank you for reporting. I Added Error handler.

There seems to be a problem logging in with the bot's token.
Make sure your bot's token is correct.
Check the set up guide -> https://github.com/Meowhal/osu-ahr#setup-1

**Comment by capthusky** [comment]
> Thank you for reporting. I Added Error handler.
> 
> There seems to be a problem logging in with the bot's token.
> Make sure your bot's token is correct.
> Check the set up guide -> https://github.com/Meowhal/osu-ahr#setup-1

Here's the new error I got, I've 3x check the exact token and not a single letter or symbol was missing. I also regenerated new token and still got the same error.

[07:43:40.487][ERROR] discord - HTTPError [ReferenceError]: AbortController is not defined
    at RequestHandler.execute (C:\Users\test\Desktop\osu-ahr-master\node_modules\discord.js\src\rest\RequestHandler.js:172:15)
    at RequestHandler.execute (C:\Users\test\Desktop\osu-ahr-master\node_modules\discord.js\src\rest\RequestHandler.js:176:19)
    at RequestHandler.push (C:\Users\test\Desktop\osu-ahr-master\node_modules\discord.js\src\rest\RequestHandler.js:50:25)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async WebSocketManager.connect (C:\Users\test\Desktop\osu-ahr-master\node_modules\discord.js\src\client\websocket\WebSocketManager.js:128:9)
    at async Client.login (C:\Users\test\Desktop\osu-ahr-master\node_modules\discord.js\src\client\Client.js:245:7)
    at async DiscordBot.start (C:\Users\test\Desktop\osu-ahr-master\src\discord\DiscordBot.ts:88:7) {
  code: 500,
  method: 'get',
  path: '/gateway/bot',
  requestData: { json: undefined, files: [] }

Is there something I need to do with the OAuth2?

**Comment by Meowhal** [comment]
Discord.js (The library I used to access discord) requires Node 16.6 or higher.
Try using the latest version of nodejs.

https://discordjs.guide/additional-info/changes-in-v13.html#before-you-start
> v13 requires Node 16.6 or higher to use, so make sure you're up to date. To check your Node version, use node -v in your terminal or command prompt, and if it's not high enough, update it! There are many resources online to help you with this step based on your host system.
